name: Build LaTeX document
on: 
  push:
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: plan.tex
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: artifacts/plan.pdf          
      #- name: Run a multi-line script
      #  run: |
      #    cp output/plan.pdf output/output.pdf
