name: Build LaTeX document
on: 
  push:
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/texlive-action/full@v1
        #- uses: xu-cheng/texlive-action/small@v1
        with:
          root_file: plan.tex
